import { useEffect, useMemo, useState } from 'react';
import { ArrowDown, ArrowUp, ArrowUpDown, Database, ExternalLink } from 'lucide-react';
import WorkspaceToolbar from './WorkspaceToolbar';

const get = (row, path) => path.split('.').reduce((value, key) => value?.[key], row);
const format = (value, key) => { if (value === null || value === undefined || value === '') return '—'; if (key === 'mintPrice' || key === 'oneTimeReward' || key === 'reward') return Number(value).toLocaleString(); if (key === 'distance') return `${Number(value).toLocaleString()} m`; if (key === 'area') return `${Math.round(Number(value)).toLocaleString()} m²`; if (key === 'yieldBoost') return `${value}×`; return String(value); };
export default function DataResults({ tool, rows, city, searched, error }) {
  const [filter,setFilter]=useState(''), [sort,setSort]=useState(null);
  useEffect(()=>{setFilter('');setSort(null);},[tool.id,rows]);
  const visibleRows=useMemo(()=>{
    const term=filter.trim().toLowerCase();
    const filtered=term?rows.filter((row)=>tool.columns.some(([key])=>String(get(row,key)??'').toLowerCase().includes(term))):rows;
    if(!sort)return filtered;
    return [...filtered].sort((a,b)=>{const left=get(a,sort.key),right=get(b,sort.key);const result=typeof left==='number'&&typeof right==='number'?left-right:String(left??'').localeCompare(String(right??''),undefined,{numeric:true});return sort.direction==='asc'?result:-result;});
  },[filter,rows,sort,tool.columns]);
  const toggleSort=(key)=>setSort((current)=>current?.key===key?{key,direction:current.direction==='asc'?'desc':'asc'}:{key,direction:'asc'});
  if (error) return <div className="m-5 border border-destructive/50 bg-destructive/10 p-5 text-sm text-destructive">{error}</div>;
  if (!searched) return <div className="flex min-h-72 flex-col items-center justify-center p-8 text-center"><Database className="h-8 w-8 text-primary"/><p className="mt-4 font-display text-2xl">Your results will appear here.</p><p className="mt-2 max-w-md text-sm text-muted-foreground">Choose a type of information, answer the simple question above, and we will handle the request.</p></div>;
  return <section className="p-5 sm:p-7"><div className="mb-5 flex items-end justify-between gap-4"><div><p className="font-mono text-[9px] uppercase tracking-[0.2em] text-primary">Workspace</p><h3 className="mt-2 font-display text-3xl">{tool.title}{city?` in ${city.name}`:''}</h3></div><span className="font-mono text-xs text-muted-foreground">Click a heading to sort</span></div>{rows.length===0?<div className="border border-dashed border-border p-10 text-center text-sm text-muted-foreground">No matching information is currently available.</div>:<><WorkspaceToolbar filter={filter} onFilter={setFilter} shown={visibleRows.length} total={rows.length}/><div className="max-h-[560px] overflow-auto border border-border"><table className="w-full min-w-[760px] border-collapse text-left"><thead className="sticky top-0 z-10 bg-secondary"><tr><th className="w-12 border-b border-r border-border px-3 py-3 text-center font-mono text-[9px] text-muted-foreground">#</th>{tool.columns.map(([key,label])=>{const active=sort?.key===key,Icon=active?(sort.direction==='asc'?ArrowUp:ArrowDown):ArrowUpDown;return <th key={label} aria-sort={active?(sort.direction==='asc'?'ascending':'descending'):'none'} className="border-b border-r border-border last:border-r-0"><button type="button" onClick={()=>toggleSort(key)} className="flex min-h-11 w-full items-center justify-between gap-3 px-4 py-3 text-left font-mono text-[9px] uppercase tracking-[0.16em] text-muted-foreground hover:bg-primary/10 hover:text-foreground">{label}<Icon className="h-3 w-3 shrink-0"/></button></th>;})}</tr></thead><tbody>{visibleRows.map((row,index)=><tr key={row.id||index} className="odd:bg-background even:bg-card/40 hover:bg-primary/5"><td className="border-b border-r border-border px-3 py-3 text-center font-mono text-[10px] text-muted-foreground">{index+1}</td>{tool.columns.map(([key])=><td key={key} className="max-w-sm border-b border-r border-border px-4 py-3 text-sm last:border-r-0">{key==='appUrl'&&row[key]?<a className="inline-flex items-center gap-1 text-primary hover:underline" href={row[key]} target="_blank" rel="noreferrer">Open <ExternalLink className="h-3 w-3"/></a>:format(get(row,key),key)}</td>)}</tr>)}</tbody></table>{visibleRows.length===0&&<div className="p-10 text-center text-sm text-muted-foreground">No rows match that filter.</div>}</div></>}</section>;
}