import { useEffect, useState } from 'react';
import { Plus } from 'lucide-react';
import { Button } from '@/components/ui/button';
import SprintComposer from './SprintComposer'; import TaskComposer from './TaskComposer'; import TaskColumn from './TaskColumn';
const columns=[['Backlog','backlog'],['In progress','in_progress'],['Review','review'],['Done','done']];
export default function RoadmapPanel({ roadmap }) {
  const [selected, setSelected] = useState(''), [addingSprint, setAddingSprint] = useState(false);
  useEffect(() => { if (!selected && roadmap.sprints.length) setSelected((roadmap.sprints.find((s)=>s.status==='active')||roadmap.sprints[0]).id); }, [roadmap.sprints, selected]);
  const sprint = roadmap.sprints.find((item)=>item.id===selected), tasks = roadmap.tasks.filter((task)=>task.sprint_id===selected);
  return <div className="mx-auto max-w-[1500px] px-5 py-8 sm:px-8"><header className="flex flex-col gap-5 border-b border-border pb-6 lg:flex-row lg:items-end lg:justify-between"><div><p className="font-mono text-[10px] uppercase tracking-[0.25em] text-primary">Delivery map</p><h2 className="mt-3 font-display text-4xl font-medium sm:text-5xl">From idea to working faucet.</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-muted-foreground">Every sprint names an outcome. Every task has one owner: the system, the interface, governance, or Unreal.</p></div><Button variant="outline" size="sm" onClick={()=>setAddingSprint(true)}><Plus/> New sprint</Button></header>
    {addingSprint&&<div className="mt-5"><SprintComposer onCreate={roadmap.createSprint} onClose={()=>setAddingSprint(false)}/></div>}
    <div className="mt-6 flex gap-2 overflow-x-auto pb-2">{roadmap.sprints.map((item)=><button key={item.id} onClick={()=>setSelected(item.id)} className={`min-h-11 whitespace-nowrap border px-4 text-left ${selected===item.id?'border-primary bg-primary/10 text-foreground':'border-border text-muted-foreground hover:text-foreground'}`}><span className="block font-mono text-[9px] uppercase tracking-[0.16em]">{item.status}</span><span className="text-sm font-medium">{item.name}</span></button>)}</div>
    {roadmap.loading?<div className="py-20 text-center text-muted-foreground">Loading roadmap…</div>:sprint?<><section className="my-6 flex flex-col gap-4 border-y border-border py-5 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-mono text-[10px] uppercase tracking-[0.18em] text-primary">Sprint objective</p><p className="mt-2 max-w-3xl font-display text-2xl">{sprint.objective}</p></div><div className="flex items-center gap-3"><select value={sprint.status} onChange={(e)=>roadmap.updateSprint(sprint.id,{status:e.target.value})} className="min-h-9 border border-border bg-background px-3 text-sm text-foreground"><option value="planned">Planned</option><option value="active">Active</option><option value="complete">Complete</option></select><TaskComposer sprintId={sprint.id} onCreate={roadmap.createTask}/></div></section><div className="grid gap-5 md:grid-cols-2 xl:grid-cols-4">{columns.map(([title,status])=><TaskColumn key={status} title={title} status={status} tasks={tasks.filter((task)=>task.status===status)} onUpdate={roadmap.updateTask} onDelete={roadmap.deleteTask}/>)}</div></>:<div className="border border-dashed border-border py-20 text-center text-muted-foreground">Create a sprint to begin.</div>}
  </div>;
}