import { useState } from 'react';
import { Plus } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
export default function TaskComposer({ sprintId, onCreate }) {
  const [open, setOpen] = useState(false), [saving, setSaving] = useState(false), [error, setError] = useState('');
  const [form, setForm] = useState({ title: '', description: '', priority: 'medium', area: 'experience' });
  const save = async (event) => { event.preventDefault(); setSaving(true); setError(''); try { await onCreate({ ...form, sprint_id: sprintId }); setForm({ title: '', description: '', priority: 'medium', area: 'experience' }); setOpen(false); } catch { setError('Task could not be added.'); } finally { setSaving(false); } };
  if (!open) return <Button size="sm" onClick={() => setOpen(true)} disabled={!sprintId}><Plus/> Add task</Button>;
  return <form onSubmit={save} className="grid gap-3 border border-primary/30 bg-card p-4 sm:grid-cols-2 lg:grid-cols-5"><Input required value={form.title} onChange={(e) => setForm({...form,title:e.target.value})} placeholder="Task title" className="lg:col-span-2"/><Textarea value={form.description} onChange={(e) => setForm({...form,description:e.target.value})} placeholder="Definition of done" className="min-h-9 lg:col-span-3"/><select value={form.area} onChange={(e) => setForm({...form,area:e.target.value})} className="min-h-9 border border-border bg-background px-3 text-sm text-foreground"><option value="experience">Experience</option><option value="hallways">Hallways</option><option value="boardroom">Boardroom</option><option value="unreal">Unreal</option><option value="operations">Operations</option></select><select value={form.priority} onChange={(e) => setForm({...form,priority:e.target.value})} className="min-h-9 border border-border bg-background px-3 text-sm text-foreground"><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option></select><div className="flex gap-2 lg:col-span-3"><Button size="sm" type="submit" disabled={saving}>{saving?'Adding…':'Add task'}</Button><Button size="sm" type="button" variant="ghost" onClick={() => setOpen(false)}>Cancel</Button>{error&&<span className="text-sm text-destructive">{error}</span>}</div></form>;
}