import { useCallback, useEffect, useState } from 'react';
import { CheckCircle2, Copy, Loader2, PlugZap } from 'lucide-react';
import { base44 } from '@/api/base44Client';
import { Button } from '@/components/ui/button';
export default function UplandConnectionPanel(){
  const [connection,setConnection]=useState({status:'loading'}),[busy,setBusy]=useState(false),[error,setError]=useState(''),[copied,setCopied]=useState(false);
  const refresh=useCallback(async()=>{const response=await base44.functions.invoke('uplandAuthStatus',{});setConnection(response.data);},[]);
  useEffect(()=>{refresh();},[refresh]);
  useEffect(()=>{if(connection.status!=='pending')return;const timer=setInterval(refresh,3000);return()=>clearInterval(timer);},[connection.status,refresh]);
  const start=async()=>{setBusy(true);setError('');try{const response=await base44.functions.invoke('startUplandAuth',{});setConnection(response.data);}catch(reason){setError(reason.response?.data?.error||reason.message);}finally{setBusy(false);}};
  const copy=async()=>{await navigator.clipboard.writeText(connection.code);setCopied(true);setTimeout(()=>setCopied(false),1500);};
  if(connection.status==='loading')return <div className="flex min-h-64 items-center justify-center"><Loader2 className="h-6 w-6 animate-spin text-primary"/></div>;
  return <section className="mx-auto max-w-3xl p-5 sm:py-12"><p className="font-mono text-[10px] uppercase tracking-[0.25em] text-primary">Player connection</p><h2 className="mt-3 font-display text-4xl">Connect your Upland identity</h2><p className="mt-3 text-sm leading-6 text-muted-foreground">Generate a one-time code, enter it in Upland, and this screen will confirm your connection automatically.</p><div className="mt-8 border border-border bg-card p-6 sm:p-8">{connection.status==='connected'?<div className="flex items-start gap-4"><CheckCircle2 className="mt-1 h-7 w-7 text-primary"/><div><h3 className="text-lg font-semibold">Upland connected</h3><p className="mt-1 text-sm text-muted-foreground">{connection.profile?.username||connection.profile?.name||'Your player'} is ready to use portfolio tools.</p></div></div>:connection.status==='pending'?<div><p className="text-sm font-medium">Enter this code in your Upland account</p><button onClick={copy} className="mt-4 flex min-h-16 w-full items-center justify-between border border-primary/50 bg-primary/10 px-5 font-mono text-2xl tracking-[0.18em] text-primary"><span>{connection.code}</span><Copy className="h-5 w-5"/></button><p className="mt-3 text-xs text-muted-foreground">{copied?'Copied.':'Waiting for approval in Upland… This page checks automatically.'}</p></div>:<div className="text-center"><PlugZap className="mx-auto h-9 w-9 text-primary"/><Button className="mt-5" onClick={start} disabled={busy}>{busy?<Loader2 className="animate-spin"/>:'Generate connection code'}</Button></div>}{error&&<p className="mt-4 text-sm text-destructive">{error}</p>}</div></section>;
}